### ISSUE TITLE
Add a title

### ISSUE THREAD

**Issue by n-kb** [jplusplus/CrawlerToolkit#14]
:'(

![screenshot from 2017-11-16 09-58-04](https://user-images.githubusercontent.com/864677/32882450-ac254ab2-cab4-11e7-80ca-95c88d8aecdf.png)

**Comment by n-kb** [comment]
I suggest "{{Name of page}} - Offshore Journalism Crawler" as title.

**Comment by pbellon** [comment]
The easiest thing for me is to go with the way Django names views, so it will be in form of:
"Select {model} to change - Offshore Journalism Crawler"
"Change {model} - Offshore Journalism Crawler" etc.. in function of the model (Feed or Article). 

However, I managed to set title to "Dashboard - Offshore Journalism Crawler" for admin homepage.
