### ISSUE TITLE
Remove debug vars from error screens

### ISSUE THREAD

**Issue by n-kb** [jplusplus/CrawlerToolkit#15]
In order to avoid this:

http://archive.is/nLOsh

![screenshot from 2017-11-16 10-05-24](https://user-images.githubusercontent.com/864677/32882762-b5f606b6-cab5-11e7-9910-bdba47213935.png)

**Comment by pbellon** [comment]
It should be ok now, the DEBUG is set to False by default in `settings_heroku`. However I added a `DEBUG` Heroku environnement variable in order to be able to debug the application without changing the code.
