### ISSUE TITLE
Don't store articles for immediate archiving on the crawler

### ISSUE THREAD

**Issue by n-kb** [jplusplus/CrawlerToolkit#17]
I thought that articles that only had `priority = true` were not stored by the crawler (i.e. sent directly from their original address), but #16 seems to show that it isn't the case. Making it so would probably save some storage space, wouldn't it?

**Comment by pbellon** [comment]
Indeed, I've not operated like this and we can do as you describe, which would save storage space.

**Comment by pbellon** [comment]
This should be the case now. Priority tagged articles are not stored anymore.
